import pandas as pd


class QueryEngine:

    def __init__(self, dataframe: pd.DataFrame):
        self.df = dataframe.copy()

        # =====================================================
        # PREPARE DATA
        # =====================================================

        if "created_at" in self.df.columns:
            self.df["created_at"] = pd.to_datetime(
                self.df["created_at"],
                errors="coerce"
            )

        if "response_time_hrs" in self.df.columns:
            self.df["response_time_hrs"] = pd.to_numeric(
                self.df["response_time_hrs"],
                errors="coerce"
            )

        if "resolution_time_hrs" in self.df.columns:
            self.df["resolution_time_hrs"] = pd.to_numeric(
                self.df["resolution_time_hrs"],
                errors="coerce"
            )

        if "customer_rating" in self.df.columns:
            self.df["customer_rating"] = pd.to_numeric(
                self.df["customer_rating"],
                errors="coerce"
            )

    # =====================================================
    # APPLY FILTERS
    # =====================================================

    def apply_filters(self, filters: dict) -> pd.DataFrame:
        """
        Apply filters generated by the LLM.

        Supports:

        - Exact categorical filters
        - Multiple categorical values
        - Numeric comparisons
        - age_hours comparisons
        """

        data = self.df.copy()

        if not filters:
            return data

        for column, value in filters.items():

            # =================================================
            # AGE HOURS FILTER
            # =================================================

            if column == "age_hours":

                if "created_at" not in data.columns:
                    raise ValueError(
                        "created_at column is required "
                        "for age_hours filtering"
                    )

                if not isinstance(value, dict):
                    raise ValueError(
                        "age_hours filter must be an object"
                    )

                operator = value.get("operator")
                filter_value = value.get("value")

                if operator not in {
                    ">",
                    "<",
                    ">=",
                    "<=",
                    "==",
                    "!="
                }:
                    raise ValueError(
                        f"Unsupported age_hours operator: "
                        f"{operator}"
                    )

                try:
                    filter_value = float(filter_value)

                except (TypeError, ValueError):
                    raise ValueError(
                        f"Invalid age_hours value: "
                        f"{filter_value}"
                    )

                # -------------------------------------------------
                # IMPORTANT:
                # Use latest dataset timestamp as reference time.
                #
                # Dataset:
                # 2024-01 -> 2024-03
                #
                # This prevents historical assessment data from
                # being compared against the real current date.
                # -------------------------------------------------

                if data["created_at"].notna().any():

                    reference_time = (
                        data["created_at"].max()
                    )

                    age_hours = (
                        reference_time
                        - data["created_at"]
                    ).dt.total_seconds() / 3600

                else:
                    return data.iloc[0:0]

                if operator == ">":
                    mask = age_hours > filter_value

                elif operator == "<":
                    mask = age_hours < filter_value

                elif operator == ">=":
                    mask = age_hours >= filter_value

                elif operator == "<=":
                    mask = age_hours <= filter_value

                elif operator == "==":
                    mask = age_hours == filter_value

                elif operator == "!=":
                    mask = age_hours != filter_value

                # Invalid dates should never match
                mask = (
                    mask
                    & data["created_at"].notna()
                )

                data = data[mask]

                continue

            # =================================================
            # NORMAL COLUMN VALIDATION
            # =================================================

            if column not in data.columns:
                raise ValueError(
                    f"Unknown column: {column}"
                )

            # =================================================
            # NUMERIC COMPARISON FILTER
            # =================================================

            if isinstance(value, dict):

                operator = value.get("operator")
                filter_value = value.get("value")

                if operator not in {
                    ">",
                    "<",
                    ">=",
                    "<=",
                    "==",
                    "!="
                }:
                    raise ValueError(
                        f"Unsupported operator: {operator}"
                    )

                numeric_data = pd.to_numeric(
                    data[column],
                    errors="coerce"
                )

                try:
                    filter_value = float(
                        filter_value
                    )

                except (TypeError, ValueError):
                    raise ValueError(
                        f"Invalid numeric value for "
                        f"{column}: {filter_value}"
                    )

                if operator == ">":
                    mask = (
                        numeric_data
                        > filter_value
                    )

                elif operator == "<":
                    mask = (
                        numeric_data
                        < filter_value
                    )

                elif operator == ">=":
                    mask = (
                        numeric_data
                        >= filter_value
                    )

                elif operator == "<=":
                    mask = (
                        numeric_data
                        <= filter_value
                    )

                elif operator == "==":
                    mask = (
                        numeric_data
                        == filter_value
                    )

                elif operator == "!=":
                    mask = (
                        numeric_data
                        != filter_value
                    )

                data = data[mask]

            # =================================================
            # MULTIPLE VALUES
            # =================================================

            elif isinstance(value, list):

                data = data[
                    data[column]
                    .astype(str)
                    .str.lower()
                    .isin(
                        [
                            str(v).lower()
                            for v in value
                        ]
                    )
                ]

            # =================================================
            # EXACT VALUE
            # =================================================

            else:

                data = data[
                    data[column]
                    .astype(str)
                    .str.lower()
                    ==
                    str(value).lower()
                ]

        return data

    # =====================================================
    # APPLY TIME RANGE
    # =====================================================

    def apply_time_range(
        self,
        data: pd.DataFrame,
        time_range: str
    ) -> pd.DataFrame:
        """
        Apply relative time ranges.

        IMPORTANT:
        Relative dates are based on the latest timestamp
        available in the dataset, not the actual current date.

        Supported:

        - all
        - today
        - this_week
        - this_month
        """

        if not time_range or time_range == "all":
            return data

        if "created_at" not in data.columns:
            raise ValueError(
                "created_at column is required "
                "for time filtering"
            )

        valid_dates = data["created_at"].dropna()

        if valid_dates.empty:
            return data.iloc[0:0]

        # =================================================
        # DATASET REFERENCE DATE
        # =================================================

        now = valid_dates.max()

        # =================================================
        # TODAY
        # =================================================

        if time_range == "today":

            start = now.normalize()

            return data[
                data["created_at"] >= start
            ]

        # =================================================
        # THIS WEEK
        # =================================================

        elif time_range == "this_week":

            start = (
                now.normalize()
                - pd.Timedelta(
                    days=now.weekday()
                )
            )

            return data[
                data["created_at"] >= start
            ]

        # =================================================
        # THIS MONTH
        # =================================================

        elif time_range == "this_month":

            start = pd.Timestamp(
                year=now.year,
                month=now.month,
                day=1
            )

            return data[
                data["created_at"] >= start
            ]

        # =================================================
        # UNSUPPORTED TIME RANGE
        # =================================================

        else:

            raise ValueError(
                f"Unsupported time range: "
                f"{time_range}"
            )

    # =====================================================
    # EXECUTE QUERY
    # =====================================================

    def execute(self, query_plan: dict):
        """
        Execute the structured query generated by Gemini.
        """

        if not isinstance(query_plan, dict):
            raise ValueError(
                "Query plan must be a dictionary"
            )

        operation = query_plan.get(
            "operation"
        )

        filters = query_plan.get(
            "filters",
            {}
        )

        if not isinstance(filters, dict):
            raise ValueError(
                "filters must be an object"
            )

        # =================================================
        # APPLY FILTERS
        # =================================================

        data = self.apply_filters(
            filters
        )

        # =================================================
        # APPLY TIME RANGE
        # =================================================

        time_range = query_plan.get(
            "time_range"
        )

        if time_range:

            data = self.apply_time_range(
                data,
                time_range
            )

        # =================================================
        # COUNT
        # =================================================

        if operation == "count":

            return {
                "count": int(len(data))
            }

        # =================================================
        # AVERAGE
        # =================================================

        elif operation == "average":

            column = query_plan.get(
                "column"
            )

            self.validate_column(
                column
            )

            value = pd.to_numeric(
                data[column],
                errors="coerce"
            ).mean()

            return {
                "average": (
                    round(
                        float(value),
                        2
                    )
                    if pd.notna(value)
                    else None
                )
            }

        # =================================================
        # SUM
        # =================================================

        elif operation == "sum":

            column = query_plan.get(
                "column"
            )

            self.validate_column(
                column
            )

            value = pd.to_numeric(
                data[column],
                errors="coerce"
            ).sum()

            return {
                "sum": round(
                    float(value),
                    2
                )
            }

        # =================================================
        # MIN
        # =================================================

        elif operation == "min":

            column = query_plan.get(
                "column"
            )

            self.validate_column(
                column
            )

            value = pd.to_numeric(
                data[column],
                errors="coerce"
            ).min()

            return {
                "min": (
                    float(value)
                    if pd.notna(value)
                    else None
                )
            }

        # =================================================
        # MAX
        # =================================================

        elif operation == "max":

            column = query_plan.get(
                "column"
            )

            self.validate_column(
                column
            )

            value = pd.to_numeric(
                data[column],
                errors="coerce"
            ).max()

            return {
                "max": (
                    float(value)
                    if pd.notna(value)
                    else None
                )
            }

        # =================================================
        # LIST
        # =================================================

        elif operation == "list":

            columns = query_plan.get(
                "columns",
                list(data.columns)
            )

            if not isinstance(
                columns,
                list
            ):
                raise ValueError(
                    "columns must be a list"
                )

            for column in columns:

                self.validate_column(
                    column
                )

            # -------------------------------------------------
            # Limit results to prevent huge responses
            # -------------------------------------------------

            limit = query_plan.get(
                "limit",
                100
            )

            try:
                limit = int(limit)

            except (
                TypeError,
                ValueError
            ):
                limit = 100

            limit = max(
                1,
                min(
                    limit,
                    500
                )
            )

            result = data[
                columns
            ].head(limit)

            return {
                "rows": (
                    result
                    .where(
                        pd.notna(result),
                        None
                    )
                    .to_dict(
                        orient="records"
                    )
                )
            }

        # =================================================
        # GROUP COUNT
        # =================================================

        elif operation == "group_count":

            group_by = query_plan.get(
                "group_by"
            )

            self.validate_column(
                group_by
            )

            result = (
                data
                .groupby(
                    group_by
                )
                .size()
                .reset_index(
                    name="count"
                )
                .sort_values(
                    "count",
                    ascending=False
                )
            )

            # -------------------------------------------------
            # Optional limit
            # -------------------------------------------------

            limit = query_plan.get(
                "limit"
            )

            if limit is not None:

                try:

                    limit = int(
                        limit
                    )

                    limit = max(
                        1,
                        limit
                    )

                    result = result.head(
                        limit
                    )

                except (
                    TypeError,
                    ValueError
                ):
                    pass

            return {
                "groups": result.to_dict(
                    orient="records"
                )
            }

        # =================================================
        # UNKNOWN OPERATION
        # =================================================

        else:

            raise ValueError(
                f"Unsupported operation: "
                f"{operation}"
            )

    # =====================================================
    # VALIDATE COLUMN
    # =====================================================

    def validate_column(
        self,
        column: str
    ):
        """
        Ensure that the requested column
        exists in the dataset.
        """

        if not column:

            raise ValueError(
                "Column was not provided"
            )

        if column not in self.df.columns:

            raise ValueError(
                f"Unknown column: {column}"
            )