import pandas as pd


class QueryEngine:

    def __init__(self, dataframe: pd.DataFrame):
        self.df = dataframe.copy()

    def apply_filters(self, filters: dict) -> pd.DataFrame:
        """
        Apply filters generated by the LLM.
        """

        data = self.df.copy()

        for column, value in filters.items():

            if column not in data.columns:
                raise ValueError(
                    f"Unknown column: {column}"
                )

            # Handle multiple values
            if isinstance(value, list):

                data = data[
                    data[column]
                    .astype(str)
                    .str.lower()
                    .isin(
                        [str(v).lower() for v in value]
                    )
                ]

            else:

                data = data[
                    data[column]
                    .astype(str)
                    .str.lower()
                    == str(value).lower()
                ]

        return data

    def execute(self, query_plan: dict):
        """
        Execute the structured query generated by Gemini.
        """

        operation = query_plan.get("operation")

        filters = query_plan.get(
            "filters",
            {}
        )

        data = self.apply_filters(filters)

        # -----------------------------------------
        # COUNT
        # -----------------------------------------

        if operation == "count":

            return {
                "count": int(len(data))
            }

        # -----------------------------------------
        # AVERAGE
        # -----------------------------------------

        elif operation == "average":

            column = query_plan.get("column")

            self.validate_column(column)

            value = pd.to_numeric(
                data[column],
                errors="coerce"
            ).mean()

            return {
                "average": (
                    round(float(value), 2)
                    if pd.notna(value)
                    else None
                )
            }

        # -----------------------------------------
        # SUM
        # -----------------------------------------

        elif operation == "sum":

            column = query_plan.get("column")

            self.validate_column(column)

            value = pd.to_numeric(
                data[column],
                errors="coerce"
            ).sum()

            return {
                "sum": round(float(value), 2)
            }

        # -----------------------------------------
        # MIN
        # -----------------------------------------

        elif operation == "min":

            column = query_plan.get("column")

            self.validate_column(column)

            value = pd.to_numeric(
                data[column],
                errors="coerce"
            ).min()

            return {
                "min": (
                    float(value)
                    if pd.notna(value)
                    else None
                )
            }

        # -----------------------------------------
        # MAX
        # -----------------------------------------

        elif operation == "max":

            column = query_plan.get("column")

            self.validate_column(column)

            value = pd.to_numeric(
                data[column],
                errors="coerce"
            ).max()

            return {
                "max": (
                    float(value)
                    if pd.notna(value)
                    else None
                )
            }

        # -----------------------------------------
        # LIST
        # -----------------------------------------

        elif operation == "list":

            columns = query_plan.get(
                "columns",
                list(data.columns)
            )

            for column in columns:
                self.validate_column(column)

            result = data[columns].head(100)

            return {
                "rows": result
                .where(pd.notna(result), None)
                .to_dict(orient="records")
            }

        # -----------------------------------------
        # GROUP COUNT
        # -----------------------------------------

        elif operation == "group_count":

            group_by = query_plan.get("group_by")

            self.validate_column(group_by)

            result = (
                data
                .groupby(group_by)
                .size()
                .reset_index(name="count")
                .sort_values(
                    "count",
                    ascending=False
                )
            )

            return {
                "groups": result.to_dict(
                    orient="records"
                )
            }

        # -----------------------------------------
        # UNKNOWN OPERATION
        # -----------------------------------------

        else:

            raise ValueError(
                f"Unsupported operation: {operation}"
            )

    def validate_column(self, column: str):

        if not column:

            raise ValueError(
                "Column was not provided"
            )

        if column not in self.df.columns:

            raise ValueError(
                f"Unknown column: {column}"
            )